var myName = "ATIQA";
console.log(myName);
var age = 19;
console.log(age);
var email = "ABC1234@gmail.com";
console.log(email);
var number = +9231522428655875;
console.log(number);
var isstudent = true;
console.log(isstudent);
var isemployed = false;
console.log(isemployed);
var address = "ABC colony,quater#5,Karaci,Pakistan";
console.log(address);
var city = "Karachi";
console.log(city);
var country = "Pakistan";
console.log(country);
var skills = "canva, fiver, content writing, resumes making, amazon virtual assistant...i.e";
console.log(skills);
var ismarried = false;
console.log(ismarried);
var height = 5.7;
console.log(height);
var matriculation = "Computer science";
console.log(matriculation);
var intermediate = "Commerce";
console.log(intermediate);
var weight = 45;
console.log(weight);
var isgraduate = false;
console.log(isgraduate);
var matriculationYear = 2020;
console.log(matriculationYear);
